baseURL = "http://example.org/"
languageCode = "en-us"
title = "Galaktik"
theme = "split-landing"

[params]
showCenterTitle = true
mainTitle = "Galaktik.io"
subTitle = "interstellar idk"
leftTitle = "Galaktik Audio"
leftSubTitle = "Audio Production and Composition"
leftJpg = "/images/audio.jpg"
leftButtonText = "Read More"
leftLink = "https://audio.galaktik.io"
rightTitle = "Galaktik Executables"
rightSubTitle = "Website Management and Software Engineering"
rightJpg = "/images/programmer.png"
rightButtonText = "Read More"
rightLink = "https://exe.galaktik.io"